### ISSUE TITLE
Can't mount dir with "gc -a mass [DIR]"

### ISSUE THREAD

**Issue by pluvium27** [HandsomeMod/gc#2]
`` 
failed to create mass storage function!  (maybe kernel module not loaded?) 
``
Device infmation:
device: Handsome Openstick 
distro: Debian 11
arch: aarch64
kernel: 5.15.0-handsomekernel+ (linux)
operating user: root

How to fix it?

**Comment by friddle** [comment]
怎么解决的？

**Comment by pluvium27** [comment]
> 怎么解决的？

我记得似乎我是将挂载点和设备弄混了而程序本身没有问题
由于我已不再使用此程序 因而如有不当之处 请新开一个 issue

**Comment by friddle** [comment]
example错了
